name: Health

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
    paths:
      - "**/*.dart"

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
        checks: "version,changelog,breaking,do-not-submit,leaking"
        fail_on: "do-not-submit"
        warn_on: "version,changelog,breaking,leaking"
        use-flutter: true
    permissions:
        pull-requests: write
