name: foo_devtools_extension
description: A Flutter web app for the package:foo DevTools extension.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  devtools_app_shared:
    path: ../../../../../../devtools_app_shared
  devtools_extensions:
    path: ../../../../../../devtools_extensions 
  dtd: ^2.2.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  devtools_app_shared:
    path: ../../../../../../devtools_app_shared
  devtools_extensions:
    path: ../../../../../../devtools_extensions 
  devtools_shared:
    path: ../../../../../../devtools_shared
